### ISSUE TITLE
Putting a negative value as cost

### ISSUE THREAD

**Issue by SnowBlitzz** [NickImpact/GTS-Sponge#1]
Currently you're able to do `/gts add {slot} {negative-value}` and in doing so, the player who purchases your Pokemon will gain that amount of money. It is easily abuseable once the knowledge of the bug is found since nobody loses anything and new money gets generated from it. 

Example: `/gts add 1 -500`
The player who buys my Pokemon will get my Pokemon and 500 cash for free.

**Comment by NickImpact** [comment]
Why do I have learn these issues while drunk lol, here's goes an attempt at a drunk fix

**Comment by SnowBlitzz** [comment]
Oh no xD I know _some_ coding so I _might_ be able to point if it's good or not once you make the commit.

**Comment by NickImpact** [comment]
Should be patched now, just compiled the fixed version, patch should be going up in a few moments

**Comment by SnowBlitzz** [comment]
Amazing. Your response was really quick lol.

**Comment by NickImpact** [comment]
Was literally passed out a minute ago so call my response a miracle

**Comment by NickImpact** [comment]
Patch is uploaded, hopefully it works (as I'm seeing sideways rn and not feeling like testing code)

**Comment by SnowBlitzz** [comment]
I've just tested. It's now fixed. Thanks!
