### ISSUE TITLE
[2.0.3] /gts clear not working

### ISSUE THREAD

**Issue by Xenoyia** [NickImpact/GTS-Sponge#16]
/gts clear - this command doesn't work with or without parameters.

![5660a6891a4190aba9e78a91071c535a](https://cloud.githubusercontent.com/assets/4874985/24982119/bbe261e8-1fd7-11e7-8eb9-00ff04e599e2.png)

Error: https://pastebin.com/QKTZdsFe

**Comment by NickImpact** [comment]
This command has since changed to a deletion of everything, rather than give everyone their pokemon back. This is open to change in the future, but will currently stand with this design for the beginning of the 2.x series.
