### ISSUE TITLE
[2.0.3] adding a random ditto egg to GTS shows the resulting pokémon

### ISSUE THREAD

**Issue by Xenoyia** [NickImpact/GTS-Sponge#17]
![a1](https://cloud.githubusercontent.com/assets/4874985/24982371/00a20206-1fd9-11e7-8fba-854879742d0d.png)

![a2](https://cloud.githubusercontent.com/assets/4874985/24982372/00a2b160-1fd9-11e7-8726-9eb5a40c643d.png)

**Comment by NickImpact** [comment]
This should be fixed in the latest snapshot

**Comment by TheEliteMaster** [comment]
Where can I download the latest snapshots?
