### ISSUE TITLE
Purchased when Cancel is clicked

### ISSUE THREAD

**Issue by SnowBlitzz** [NickImpact/GTS-Sponge#2]
A player on the server 'accidentally' purchased something he did not want. By accident, I mean, he clicked Cancel but it made him buy it anyway. He then got an error message in chat which shows:
`[15:13:37] [Client thread/INFO]: [CHAT] GTS | You successfully purchased the Froakie for $25,000
[15:13:37] [Client thread/INFO]: [CHAT] A missing message setup was detected for path: Messages.GTS.Purchase.Failed`

**Comment by NickImpact** [comment]
Good to note, guess I worked a little too late one night and assumed I had this solved. Plus, looks like I forgot to add a message situation to the message configuration, will have this patched in the morning.

**Comment by NickImpact** [comment]
It actually looks to be that instead of clicking cancel, he had to have clicked the confirm button. He somehow managed to generate that second message though likely from a small case of lag, as that second message is meant to be the scenario when the listing is no longer present in the stored data.

**Comment by SnowBlitzz** [comment]
That is strange. It does seem like a rare case though as it has only happened to him so far.

**Comment by NickImpact** [comment]
I'm going to close this issue for now, should anything pop up again, let me know
