### ISSUE TITLE
Player info doesnt work

### ISSUE THREAD

**Issue by Earthplate** [NickImpact/GTS-Sponge#3]

**Comment by NickImpact** [comment]
What exactly doesn't work? This is very hard to fix with no information

**Comment by Earthplate** [comment]
NVM I'm dumb my fault(I thought it was meant to do show something itself idk if u want to change it to the user's skull, but i realized its purpose)  I'm sorry about leaving stupid issues with barely any info btw. I appreciate everything you do.
