### ISSUE TITLE
Search Command Only works on the first pokemon in the gts

### ISSUE THREAD

**Issue by Earthplate** [NickImpact/GTS-Sponge#5]

**Comment by NickImpact** [comment]
This issue should have been fixed in the latest release, care to check?

**Comment by Earthplate** [comment]
Yea the search still only works for first pokemon on version 1.3.5. Not sure if theres another one, I don't see one.

**Comment by NickImpact** [comment]
Huh, perhaps I didn't push that fix. I'll do that in a few moments

**Comment by NickImpact** [comment]
I see what happened, I wrote the fix into the wrong location of GTS (Have two now due to me recently throwing everything on dropbox for cross-platform ease). I'll upload the fix in the next few minutes!
