### ISSUE TITLE
[Feature] /gts search Extra Parameters

### ISSUE THREAD

**Issue by Rasgnarok** [NickImpact/GTS-Sponge#6]
Would be neat to add parameters defined by /pokegive and /pokeedit, so as to refine search results.
Format: `/gts search <Pokemon> [--growth|--gender|--nature|--shiny|--ability|--evAtk|--ivSpeed|--friendship|--move|--minPrice|--maxPrice|-seller]`
(of course, did not list all stats because hell that's long) Note, min/maxPrice and Seller would be parameters taken from GTS itself - you can search for pricing, and by seller username.
The listing for PokeEdit has most parameters: http://pixelmonmod.com/wiki/index.php?title=PixelExtras

**Comment by NickImpact** [comment]
Other than fixing the reversed logic, thank god I'm done with this! Well, that is, until more flags are requested :)
